kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/NakupovalniSeznami
      connection-url: jdbc:postgresql://localhost:5432/nakupovalni_seznami
      username: postgres
      password: postgres
      max-pool-size: 20